services:
  tgbot:
    build: .
    container_name: tgbot_service
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    environment:
      ZT_NETWORK_ID: "${ZT_NETWORK_ID:-8185934e6af6ceb3}"
      TG_TOKEN: "${TG_TOKEN}"
      TG_BD_NET: "${TG_BD_NET:-}"
      TG_DASHBOARD_PASSWORD: "${TG_DASHBOARD_PASSWORD}"
      TG_DASHBOARD_LISTEN_PORT: "${TG_DASHBOARD_LISTEN_PORT:-8080}"
      TG_LOG_PATH: "${TG_LOG_PATH:-/app/logs/app.log}"
      TG_DB_PATH: "${TG_DB_PATH:-/app/data/bot.db}"
      TG_ADMIN_SESSION_MAX_AGE_SECONDS: "${TG_ADMIN_SESSION_MAX_AGE_SECONDS:-3600}"
      TG_ADMIN_SESSION_IDLE_SECONDS: "${TG_ADMIN_SESSION_IDLE_SECONDS:-900}"
      TG_WEB_PAGE_URL_1: "${TG_WEB_PAGE_URL_1:-https://joinzt.com/addnetwork?nwid=8185934e6af6ceb3&v=1}"
      TG_WEB_PAGE_URL_2: "${TG_WEB_PAGE_URL_2:-https://joinzt.com/addnetwork?nwid=8185934e6af6ceb3&v=1}"
      TG_INSTRUCTION_ARTICLE_URL: "${TG_INSTRUCTION_ARTICLE_URL}"
      TG_ADMIN_CHAT_ID: "${TG_ADMIN_CHAT_ID}"
      TG_BOT_USERNAME: "${TG_BOT_USERNAME:-}"
    volumes:
      - zt_data:/var/lib/zerotier-one
      - ./bot_data:/app/data
      - ./logs:/app/logs


volumes:
  zt_data:


